### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by edpil02** [lucagouty/nzxt-kraken-image-generator#1]
Is it possible to  port it to  linux easily.
.Thanks

**Comment by lucagouty** [comment]
I don't have a Linux installed so we'd need someone else to take care of it

Anyway this wasn't really meant to be widely used, I just wanted to share my work in case someone could use it on mac.

You should have a look at https://github.com/ProtozeFOSS/KrakenZPlayground or the script @th3voic3 shared : https://github.com/liquidctl/liquidctl/pull/479#issuecomment-1250328754

**Comment by edpil02** [comment]
I have already try  your proposals.
I'm not a programmer and i just wanted help or ideas to  try porting your work on linux.

Sorry for the inconvenience.
